name: dynamic_cache
description: A complete in-memory cache in Flutter. Inspired by IMemoryCache (Microsoft.Extensions.Caching.Memory.) from C# .
version: 0.0.6
repository: https://github.com/rdrgbaioco/dynamic_cache

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter: