name: dynamic_cache
description: A complete in-memory cache in Flutter. Inspired by IMemoryCache from C# and Others tools.
version: 1.0.0
repository: https://github.com/rdrgbaioco/dynamic_cache

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter: